name: Deploy Test Branch to FTP

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create db_config.php from template
        run: |
          sed -e "s|{{DB_HOST}}|${{ secrets.DB_HOST_TEST }}|g" \
              -e "s|{{DB_USERNAME}}|${{ secrets.DB_USERNAME_TEST }}|g" \
              -e "s|{{DB_PASSWORD}}|${{ secrets.DB_PASSWORD_TEST }}|g" \
              -e "s|{{DB_NAME}}|${{ secrets.DB_NAME_TEST }}|g" \
              includes/db_config.template.php > includes/db_config.php

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST_TEST }}
          username: ${{ secrets.FTP_USER_TEST }}
          password: ${{ secrets.FTP_PASS_TEST }}
          local-dir: ./ 
          exclude: |
            .git
            .git/**
            .github
            .github/**
            .gitignore
            db
            db/**
            includes/db_config.template.php
            README.md
            LICENSE
            *.zip
            *.bak